// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1lc7JvnwyYHsld8fNG3_OIIUA2pidh0',
    appId: '1:495177119332:web:805cbc4b2b886c08ad5171',
    messagingSenderId: '495177119332',
    projectId: 'watchhub-project-74e0d',
    authDomain: 'watchhub-project-74e0d.firebaseapp.com',
    storageBucket: 'watchhub-project-74e0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5HO8KowTgN_XrCDEJKqAE8ujKarL96I4',
    appId: '1:495177119332:android:aaa00302b84fcb30ad5171',
    messagingSenderId: '495177119332',
    projectId: 'watchhub-project-74e0d',
    storageBucket: 'watchhub-project-74e0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ogGF-_yMAC27DOKNwnyaLhWwcG-IxXI',
    appId: '1:495177119332:ios:e4c7616629f30643ad5171',
    messagingSenderId: '495177119332',
    projectId: 'watchhub-project-74e0d',
    storageBucket: 'watchhub-project-74e0d.firebasestorage.app',
    iosBundleId: 'com.watchhub.watchhubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ogGF-_yMAC27DOKNwnyaLhWwcG-IxXI',
    appId: '1:495177119332:ios:e4c7616629f30643ad5171',
    messagingSenderId: '495177119332',
    projectId: 'watchhub-project-74e0d',
    storageBucket: 'watchhub-project-74e0d.firebasestorage.app',
    iosBundleId: 'com.watchhub.watchhubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM1lc7JvnwyYHsld8fNG3_OIIUA2pidh0',
    appId: '1:495177119332:web:db9e5e482ed91ecbad5171',
    messagingSenderId: '495177119332',
    projectId: 'watchhub-project-74e0d',
    authDomain: 'watchhub-project-74e0d.firebaseapp.com',
    storageBucket: 'watchhub-project-74e0d.firebasestorage.app',
  );
}